import express from "express";
import { createServer as createViteServer } from "vite";
import path from "path";
import cors from "cors";
import sharp from "sharp";
import multer from "multer";
import JSZip from "jszip";
import fs from "fs/promises";

const app = express();
const PORT = process.env.PORT || 3000;

// Middleware
app.use(cors());
app.use(express.json());

// Configure multer for file uploads
const upload = multer({
  dest: path.join(process.cwd(), "uploads"),
  limits: { fileSize: 50 * 1024 * 1024 }, // 50MB limit
});

// Ensure uploads directory exists
async function ensureUploadsDir() {
  try {
    await fs.mkdir(path.join(process.cwd(), "uploads"), { recursive: true });
  } catch (err) {
    console.error("Error creating uploads directory:", err);
  }
}

// Health check
app.get("/api/health", (req, res) => {
  res.json({ status: "ok" });
});

// Image processing endpoint
app.post("/api/upscale", upload.array("images", 100), async (req, res) => {
  try {
    const files = req.files as Express.Multer.File[];
    if (!files || files.length === 0) {
      return res.status(400).json({ error: "No files uploaded" });
    }

    const scale = parseInt(req.body.scale) || 2;
    const sharpen = req.body.sharpen === "true";
    const denoise = req.body.denoise === "true";
    const color = req.body.color === "true";

    const zip = new JSZip();
    const folder = zip.folder(`Super_Upscaler_${scale}x`);
    
    // Add README
    folder.file("README.txt", "Generated by Super Upscaler Pro.\nThank you for supporting us on Ko-fi!");

    // Process each image
    for (const file of files) {
      let image = sharp(file.path);
      
      // Get original metadata
      const metadata = await image.metadata();
      const width = metadata.width || 0;
      const height = metadata.height || 0;
      
      // Resize
      image = image.resize(width * scale, height * scale, {
        kernel: sharp.kernel.lanczos3,
      });

      // Apply sharpening
      if (sharpen) {
        image = image.sharpen({
          sigma: scale >= 4 ? 1.5 : 1.0,
          flat: 1,
          jagged: 2,
        });
      }

      // Apply denoise (median filter)
      if (denoise) {
        image = image.median(3);
      }

      // Apply vibrance/color boost
      if (color) {
        image = image.modulate({
          brightness: 1,
          saturation: 1.15,
          hue: 0,
        });
      }

      // Convert to buffer
      const buffer = await image.png().toBuffer();
      
      // Add to zip
      const originalName = file.originalname;
      const newName = originalName.replace(/\.[^/.]+$/, "") + `_x${scale}.png`;
      folder.file(newName, buffer);

      // Clean up uploaded file
      await fs.unlink(file.path);
    }

    // Generate zip
    const zipBuffer = await zip.generateAsync({ type: "nodebuffer" });
    
    res.set({
      "Content-Type": "application/zip",
      "Content-Disposition": `attachment; filename="Super_Upscaler_Pro_Result.zip"`,
    });
    
    res.send(zipBuffer);
  } catch (error) {
    console.error("Processing error:", error);
    res.status(500).json({ error: "Image processing failed" });
    
    // Clean up any remaining uploaded files
    if (req.files) {
      const files = req.files as Express.Multer.File[];
      for (const file of files) {
        try {
          await fs.unlink(file.path);
        } catch (e) {
          // Ignore cleanup errors
        }
      }
    }
  }
});
// Раздача статических файлов и главной страницы
app.use(express.static(process.cwd()));
app.get('*', (req, res) => {
    res.sendFile(path.join(process.cwd(), 'index.html'));
});


// Start server
async function startServer() {
  await ensureUploadsDir();
  
  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server running on http://localhost:${PORT}`);
  });
}

startServer();